; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_build.filesystem = littlefs
board_upload.flash_size = 16MB
upload_protocol = esptool
upload_resetmethod = nodemcu
upload_port = /dev/tty.usbmodem5B8F0407051
monitor_speed = 115200
board_build.partitions = partitions.csv
build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
	marian-craciunescu/ESP32Ping@^1.7
	arduino-libraries/NTPClient@^3.2.1
	fastled/FastLED@^3.7.0

